from django.contrib import admin
from .models import * 
# Register your models here.
admin.site.register(TotalVisitorCount)
admin.site.register(Shortlisted_Candidates)
admin.site.register(ProfileViews)
admin.site.register(AppliedJobs)
admin.site.register(JobView)
admin.site.register(Country)
admin.site.register(State)
admin.site.register(City)
admin.site.register(MyProfile)
admin.site.register(JobCategory)
admin.site.register(Industry)
admin.site.register(SubmitJob)
admin.site.register(AccountSettings)
admin.site.register(ChangePassword)
admin.site.register(Education)
admin.site.register(UG)
admin.site.register(PG)