# Generated by Django 5.1.1 on 2024-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='User/Profile/images')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('resume', models.FileField(upload_to='User/Profile/Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Workexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_job_title', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
                ('is_current_company', models.BooleanField(default='True')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notice_period', models.CharField(blank=True, choices=[('Immediately available', 'Immediately available'), ('15 days', '15 days'), ('30 days', '30 days'), ('45 days', '45 days'), ('2 Months', '2 Months'), ('3 Months', '3 Months')], max_length=50, null=True)),
                ('in_office', models.BooleanField(default=False)),
                ('hybrid', models.BooleanField(default=False)),
                ('work_from_home', models.BooleanField(default=False)),
                ('employment_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], max_length=50, null=True)),
                ('current_salary', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
