# Generated by Django 5.1.1 on 2024-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_city_country_institute_languange_passingyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_details',
            name='passing_year',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='education_details',
            name='passing_year_temp',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='PassingYear',
        ),
    ]
