# Generated by Django 5.1.1 on 2024-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_education_details_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='last_used',
            field=models.DateTimeField(),
        ),
    ]
