# Generated by Django 5.1.1 on 2024-11-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0039_alter_user_managers'),
        ('user', '0007_userprofile_total_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry', to='user.preferreddepartmentfunction'),
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobportalapp.submitjob')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'job_id')},
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_experience', to='user.years'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
