# Generated by Django 5.1.1 on 2024-11-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_years_userprofile_industry_savedjobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='years',
            name='years',
        ),
        migrations.AddField(
            model_name='years',
            name='experience_level',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='user.years'),
        ),
    ]
