# Generated by Django 5.1.1 on 2024-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_years_years_years_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='work_permit_for_USA',
            field=models.CharField(choices=[('Green Card holder', 'Green Card holder'), ('Have L1 Visa', 'Have L1 Visa'), ('US Citizen', 'US Citizen'), ('TN Permit Holder', 'TN Permit Holder'), ('Have H1 Visa', 'Have H1 Visa'), ('I have Work Authorization', 'I have Work Authorization'), ('Authorized to work in the US', 'Authorized to work in the US'), ('No US Work authorization', 'No US Work authorization')], max_length=100),
        ),
    ]
