# Generated by Django 5.1.1 on 2024-11-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_persondetails_work_permit_for_usa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetails',
            name='category',
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='resident_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_details_resident_status', to='user.country'),
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='work_permit_for_other_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_details_country', to='user.country'),
        ),
    ]
