# Generated by Django 5.1.1 on 2024-11-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_education_details_passing_year_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondetails',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
