# Generated by Django 5.1.1 on 2024-11-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_persondetails_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='language_page',
            name='languageskill',
            field=models.CharField(blank=True, choices=[('Read', 'Read'), ('Write', 'Write'), ('Speak', 'Speak')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='functional_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functional_area', to='user.preferredjobtitle'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='months',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('2 month', '2 month'), ('3 month', '3 month'), ('4 month', '4 month'), ('5 month', '5 month'), ('6 month', '6 month'), ('7 month', '7 month'), ('8 month', '8 month'), ('9 month', '9 month'), ('10 month', '10 month'), ('11 month', '11 month'), ('12 month', '12 month')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='language_page',
            name='languange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.language'),
        ),
        migrations.DeleteModel(
            name='Languange',
        ),
    ]
