# Generated by Django 5.1.1 on 2024-11-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_language_language_page_languageskill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language_page',
            old_name='languange',
            new_name='language',
        ),
    ]
