# Generated by Django 5.1.1 on 2024-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_languange_language_page_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='months',
            new_name='total_months',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
