# Generated by Django 5.1.1 on 2024-12-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_months_userprofile_total_months_and_more'),
    ]

    operations = [
       migrations.RemoveField(
            model_name='Education_Details',
            name='passing_year',
        ),
        migrations.AddField(
            model_name='Education_Details',
            name='passing_year',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_loaction', to='user.city'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_months',
            field=models.CharField(blank=True, choices=[('1 month', '1 month'), ('2 months', '2 months'), ('3 months', '3 months'), ('4 months', '4 months'), ('5 months', '5 months'), ('6 months', '6 months'), ('7 months', '7 months'), ('8 months', '8 months'), ('9 months', '9 months'), ('10 months', '10 months'), ('11 months', '11 months')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='workplace',
            field=models.CharField(blank=True, choices=[('in_office', 'In-Office'), ('hybrid', 'Hybrid'), ('work_from_home', 'Work from Home'), ('remote', 'Remote')], max_length=150, null=True),
        ),
    ]
