# Generated by Django 5.1.1 on 2024-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_education_details_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education_details',
            name='passing_year',
            field=models.DateField(null=True),
        ),
    ]
