# Generated by Django 5.1.1 on 2024-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=70, null=True)),
                ('lastname', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appliedjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedjobs_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Changepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password', models.CharField(blank=True, max_length=90, null=True)),
                ('new_password', models.CharField(blank=True, max_length=90, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('mobile_web_developer', 'Mobile Web Developer'), ('web_developer', 'Web Developer'), ('python_developer', 'Python Developer'), ('react_developer', 'React Developer')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Myprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Myprofile/Image')),
                ('employee_Name', models.CharField(blank=True, max_length=80, null=True)),
                ('website', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_size', models.IntegerField()),
                ('Founded_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=90, null=True)),
                ('phone_number', models.IntegerField()),
                ('about_company', models.TextField(blank=True, max_length=160, null=True)),
                ('address', models.TextField(blank=True, max_length=180, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('Canada', 'Canada'), ('America', 'America'), ('Australia', 'Australia'), ('United Kingdom', 'United Kingdom'), ('Germany', 'Germany')], max_length=90)),
                ('city', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Toronto', 'Toronto'), ('New York', 'New York'), ('London', 'London')], max_length=90)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(choices=[('Telangana', 'Telangana'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Ontario', 'Ontario'), ('New York', 'New York'), ('California', 'California')], max_length=100)),
                ('map_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('jobdescription', models.TextField()),
                ('jobCategory', models.CharField(choices=[('Ui Developer', 'Ui Developer'), ('React', 'React'), ('Angular', 'Angular')], max_length=100)),
                ('jobtype', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Hourly-Contract', 'Hourly Contract'), ('Fixed-Price', 'Frice-Price')], max_length=40)),
                ('salary', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], max_length=50)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('skills', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.CharField(choices=[('Expert', 'Expert'), ('Intermediate', 'Intermediate'), ('No Experience', 'No Experience')], max_length=50)),
                ('location', models.CharField(choices=[('Hyderabad TS', 'Hyderabad TS'), ('Bangalore KT ', 'Bangalore KT '), ('Mumbai MH', 'Mumbai MH'), ('Delhi DL', 'Delhi DL')], max_length=100)),
                ('Industry', models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Software Industry', 'Software Industry'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance')], max_length=50)),
                ('english_fluency', models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Excellent', 'Excellent')], max_length=90)),
                ('upload_file', models.FileField(upload_to='JobDetails/File')),
                ('address', models.TextField()),
                ('country', models.CharField(choices=[('India', 'India'), ('Canada', 'Canada'), ('USA', 'USA'), ('UK', 'UK'), ('Germany', 'Germany')], max_length=100)),
                ('city', models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Sacramento', 'Sacramento'), ('Albany', 'Albany'), ('Toronto', 'Toronto')], max_length=100)),
                ('state', models.CharField(choices=[('Telangana', 'TS'), ('Karnataka', 'KA'), ('Maharashtra', 'MH')], max_length=100)),
                ('map_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_view', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shortlisted_Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalVisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_count', models.IntegerField()),
            ],
        ),
    ]
