# Generated by Django 5.1.1 on 2024-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0002_alter_myprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='photo',
            field=models.ImageField(upload_to='Myprofile/Images'),
        ),
    ]
