# Generated by Django 5.1.1 on 2024-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0004_city_country_alter_myprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Myprofile/Images'),
        ),
    ]
