# Generated by Django 5.1.1 on 2024-10-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0005_alter_myprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newjob',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.city'),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.country'),
        ),
        migrations.AlterField(
            model_name='newjob',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.state'),
        ),
    ]
