# Generated by Django 5.1.1 on 2024-10-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0006_alter_newjob_city_alter_newjob_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newjob',
            new_name='Submitjob',
        ),
    ]
