# Generated by Django 5.1.1 on 2024-10-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0007_rename_newjob_submitjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitjob',
            name='Industry',
        ),
        migrations.AddField(
            model_name='submitjob',
            name='number_of_positions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_city_set', to='jobportalapp.city'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='jobCategory',
            field=models.CharField(choices=[('Ui Developer', 'Ui Developer'), ('React', 'React'), ('Angular', 'Angular'), ('Backend Developer', 'Backend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Data Scientist', 'Data Scientist'), ('DevOps Engineer', 'DevOps Engineer'), ('Mobile Developer', 'Mobile Developer'), ('Web Designer', 'Web Designer'), ('Software Engineer', 'Software Engineer'), ('Quality Assurance', 'Quality Assurance'), ('System Analyst', 'System Analyst'), ('Database Administrator', 'Database Administrator'), ('Network Engineer', 'Network Engineer'), ('Cloud Engineer', 'Cloud Engineer'), ('Project Manager', 'Project Manager'), ('Product Manager', 'Product Manager'), ('Technical Writer', 'Technical Writer'), ('Cybersecurity Analyst', 'Cybersecurity Analyst'), ('Business Analyst', 'Business Analyst'), ('Game Developer', 'Game Developer'), ('AI Engineer', 'AI Engineer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_location_set', to='jobportalapp.city'),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='industry',
            field=models.CharField(choices=[('IT', 'IT'), ('Marketing', 'Marketing'), ('Software Industry', 'Software Industry'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Real Estate', 'Real Estate'), ('Telecommunications', 'Telecommunications'), ('Construction', 'Construction'), ('Transportation', 'Transportation'), ('Energy', 'Energy'), ('Legal', 'Legal'), ('Aerospace', 'Aerospace'), ('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Biotechnology', 'Biotechnology'), ('Media & Entertainment', 'Media & Entertainment'), ('Consulting', 'Consulting'), ('E-commerce', 'E-commerce'), ('Government', 'Government'), ('Human Resources', 'Human Resources'), ('Insurance', 'Insurance'), ('Nonprofit', 'Nonprofit'), ('Pharmaceutical', 'Pharmaceutical'), ('Public Relations', 'Public Relations'), ('Supply Chain', 'Supply Chain'), ('Tourism', 'Tourism'), ('Food & Beverage', 'Food & Beverage'), ('Environmental Services', 'Environmental Services'), ('Mining', 'Mining'), ('Textile', 'Textile'), ('Security Services', 'Security Services'), ('Fitness & Wellness', 'Fitness & Wellness'), ('Logistics', 'Logistics'), ('Venture Capital', 'Venture Capital'), ('Architecture', 'Architecture'), ('Event Management', 'Event Management'), ('Fashion', 'Fashion'), ('Sports', 'Sports'), ('Renewable Energy', 'Renewable Energy'), ('Research & Development', 'Research & Development'), ('Shipping', 'Shipping'), ('Gaming', 'Gaming'), ('Electronics', 'Electronics')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
