# Generated by Django 5.1.1 on 2024-10-04 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0008_remove_submitjob_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='accountsettings',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='accountsettings',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='employee_Name',
            new_name='employee_name',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='Founded_date',
            new_name='founded_date',
        ),
        migrations.RenameField(
            model_name='submitjob',
            old_name='jobdescription',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='submitjob',
            old_name='jobtitle',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='submitjob',
            name='jobCategory',
        ),
        migrations.RemoveField(
            model_name='submitjob',
            name='jobtype',
        ),
        migrations.AddField(
            model_name='submitjob',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Hourly-Contract', 'Hourly Contract'), ('Fixed-Price', 'Fixed-Price')], default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobview',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='MyProfile/Images'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.industry'),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.jobcategory'),
        ),
    ]
