# Generated by Django 5.1.1 on 2024-10-04 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0009_industry_jobcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettings',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='accountsettings',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='job_category',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobview',
            name='job_title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='about_company',
            field=models.TextField(default=None, max_length=160),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='address',
            field=models.TextField(default=None, max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='category',
            field=models.CharField(default='Not Specified', max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_profiles', to='jobportalapp.city'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_profiles', to='jobportalapp.country'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='employee_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_profiles', to='jobportalapp.state'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='english_fluency',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Excellent', 'Excellent')], max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='experience',
            field=models.CharField(blank=True, choices=[('Expert', 'Expert'), ('Intermediate', 'Intermediate'), ('No Experience', 'No Experience')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='JobDetails/File'),
        ),
    ]
