# Generated by Django 5.1.1 on 2024-10-04 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0010_rename_first_name_accountsettings_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='job_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.jobcategory'),
            preserve_default=False,
        ),
    ]
