# Generated by Django 5.1.1 on 2024-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0012_alter_country_name_alter_city_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediate', models.CharField(choices=[('Any Inter', 'Any Inter'), ('MPC', 'MPC'), ('ÇEC', 'CEC')], max_length=150)),
                ('UG', models.CharField(choices=[('Any Graduate', 'Any Graduate'), ('Bsc', 'Bsc'), ('B Com', 'B Com'), ('BA', 'BA')], max_length=150)),
                ('PG', models.CharField(choices=[('Any Postgraduate', 'Any Postgraduate'), ('MBA', 'MBA'), ('MCA', 'MCA')], max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='submitjob',
            name='map_location',
        ),
        migrations.AddField(
            model_name='submitjob',
            name='about_comapny',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
