# Generated by Django 5.1.1 on 2024-10-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0013_education_remove_submitjob_map_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitjob',
            old_name='about_comapny',
            new_name='about_company',
        ),
    ]
