# Generated by Django 5.1.1 on 2024-10-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0014_rename_about_comapny_submitjob_about_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitjob',
            name='upload_file',
        ),
    ]
