# Generated by Django 5.1.1 on 2024-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0015_remove_submitjob_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ssc',
            field=models.CharField(choices=[('SSC', 'SSC')], default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitjob',
            name='work_mode',
            field=models.CharField(choices=[('Work from office', 'Work from office'), ('Work from Home', 'Work from Home'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default=None, max_length=50),
            preserve_default=False,
        ),
    ]
