# Generated by Django 5.1.1 on 2024-10-08 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0017_pg_ug_remove_education_pg_remove_education_ug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='intermediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='intermediate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.intermediate'),
        ),
    ]
