# Generated by Django 5.1.1 on 2024-10-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0018_intermediate_alter_education_intermediate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='email',
            field=models.EmailField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='firstname',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='lastname',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='confirm_password',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='new_password',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changepassword',
            name='old_password',
            field=models.CharField(default=None, max_length=90),
            preserve_default=False,
        ),
    ]
