# Generated by Django 5.1.1 on 2024-10-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0019_alter_accountsettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ssc',
            field=models.CharField(blank=True, choices=[('SSC', 'SSC')], max_length=150, null=True),
        ),
    ]
