# Generated by Django 5.1.1 on 2024-10-09 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0020_alter_education_ssc'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitjob',
            name='intermediate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.intermediate'),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='pg_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.pg'),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='ssc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='ug_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobportalapp.ug'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
