# Generated by Django 5.1.1 on 2024-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0021_submitjob_intermediate_submitjob_pg_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='ssc',
            field=models.CharField(blank=True, choices=[('SSC', 'SSC')], max_length=50, null=True),
        ),
    ]
