# Generated by Django 5.1.1 on 2024-10-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0022_alter_submitjob_ssc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitjob',
            old_name='salary',
            new_name='salary_type',
        ),
        migrations.AddField(
            model_name='submitjob',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitjob',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
