# Generated by Django 5.1.1 on 2024-10-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0023_rename_salary_submitjob_salary_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
