# Generated by Django 5.1.1 on 2024-10-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0024_alter_submitjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitjob',
            name='location',
        ),
    ]
