# Generated by Django 5.1.1 on 2024-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0026_profilephoto_submitjob_city_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='experience',
            field=models.CharField(blank=True, choices=[('Expert', 'Expert'), ('Intermediate', 'Intermediate'), ('Fresher', 'Fresher')], max_length=50, null=True),
        ),
    ]
