# Generated by Django 5.1.1 on 2024-10-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0027_alter_submitjob_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.industry'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.jobcategory'),
        ),
    ]
