# Generated by Django 5.1.1 on 2024-10-23 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0028_alter_submitjob_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitjob',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.industry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='job_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.jobcategory'),
            preserve_default=False,
        ),
    ]
