# Generated by Django 5.1.1 on 2024-10-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0030_submitjob_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='category',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='functional_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.jobcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.industry'),
        ),
    ]
