# Generated by Django 5.1.1 on 2024-10-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0032_submitjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitjob',
            name='status',
        ),
        migrations.AddField(
            model_name='submitjob',
            name='job_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
