# Generated by Django 5.1.1 on 2024-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0033_remove_submitjob_status_submitjob_job_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmitJobs',
        ),
        migrations.AddField(
            model_name='submitjob',
            name='company_logo',
            field=models.ImageField(default=None, upload_to='SubmitJob/Companylogos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submitjob',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='max_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submitjob',
            name='min_experience',
            field=models.IntegerField(default=0),
        ),
    ]
