# Generated by Django 5.1.1 on 2024-11-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0034_delete_submitjobs_submitjob_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='CompanyLogo/')),
                ('company_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='company_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='intermediate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intermediate', to='jobportalapp.intermediate'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='pg_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_course', to='jobportalapp.pg'),
        ),
        migrations.AlterField(
            model_name='submitjob',
            name='ug_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_course', to='jobportalapp.ug'),
        ),
    ]
