# Generated by Django 5.1.1 on 2024-11-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0035_companyprofile_delete_profilephoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitjob',
            old_name='city_location',
            new_name='job_location',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='submitjob',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='submitjob',
            name='company_name',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='MyProfile/Companylogos'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='company_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='company_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Govt', 'Govt')], default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myprofile',
            name='headquarter_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter_location', to='jobportalapp.city'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='founded_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='industry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.industry'),
            preserve_default=False,
        ),
    ]
