# Generated by Django 5.1.1 on 2024-11-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0036_rename_city_location_submitjob_job_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_profile_from_recruiters', models.BooleanField(default=False)),
                ('deactivate_account', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email_Push_Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_new_jobs', models.BooleanField(default=True)),
                ('follow_up_credited', models.BooleanField(default=False)),
                ('follow_up_used', models.BooleanField(default=False)),
                ('promotional', models.BooleanField(default=False)),
                ('chat_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountSettings',
        ),
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
