# Generated by Django 5.1.1 on 2024-11-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0039_alter_user_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
