# Generated by Django 5.1.1 on 2024-11-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0040_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'Super Admin')], default='user', max_length=10),
        ),
    ]
